version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8999:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'America/Chicago' #this is the time zone
      FTLCONF_LOCAL_IPV4: 172.25.0.4
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
        - traefik.http.routers.pihole.rule=Host(`pihole.azath`)
        - traefik.http.services.pihole.loadbalancer.server.port=8999
        - traefik.enable=true

networks:
  traefik-proxy:
    external: true


